version: '3'

services:
  db:
    container_name: "${db_container}"
    image: mariadb:latest 
    volumes:
      - wp_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    restart: unless-stopped
    networks:
      - internal
  wp:
    container_name: "${wp_container}"
    image: wordpress:latest
    ports:
      - 8080:80
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./plugins:/var/www/html/wp-content/plugins/ 
      - ./themes:/var/www/html/wp-content/themes/ 
      - ./uploads:/var/www/html/wp-content/uploads/ 
      - /var/www/html
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_CONFIG_EXTRA: |
                    define('WP_HOME', '${HOST_URL}');
                    define('WP_SITEURL', '${HOST_URL}');
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - internal
  wpcli:
    container_name: "${wpcli_container}"
    image: wordpress:cli
    volumes_from:
     - wp
     - db
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - /var/www/html
    depends_on:
      - db
      - wp    
    environment: 
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
    networks:
      - internal
volumes:
  wp_data:
networks:
  internal:
    driver: bridge